<?php

namespace ContainerHBSZ1zw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BhO19p3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bhO19p3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bhO19p3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'course' => ['privates', '.errored..service_locator.bhO19p3.App\\Entity\\Courses', NULL, 'Cannot autowire service ".service_locator.bhO19p3": it references class "App\\Entity\\Courses" but no such service exists.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'course' => 'App\\Entity\\Courses',
            'em' => '?',
        ]);
    }
}
