<?php

namespace ContainerHBSZ1zw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HQ0iuw7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hQ0iuw7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hQ0iuw7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'student' => ['privates', '.errored..service_locator.hQ0iuw7.App\\Entity\\Students', NULL, 'Cannot autowire service ".service_locator.hQ0iuw7": it references class "App\\Entity\\Students" but no such service exists.'],
        ], [
            'em' => '?',
            'student' => 'App\\Entity\\Students',
        ]);
    }
}
