<?php

namespace ContainerHBSZ1zw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IR1PjSXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IR1PjSX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IR1PjSX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'class' => ['privates', '.errored..service_locator.IR1PjSX.App\\Entity\\Classes', NULL, 'Cannot autowire service ".service_locator.IR1PjSX": it references class "App\\Entity\\Classes" but no such service exists.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'class' => 'App\\Entity\\Classes',
            'em' => '?',
        ]);
    }
}
