<?php

namespace ContainerHBSZ1zw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6U4gQnZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6U4gQnZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6U4gQnZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cr' => ['privates', 'App\\Repository\\CoursesRepository', 'getCoursesRepositoryService', true],
        ], [
            'cr' => 'App\\Repository\\CoursesRepository',
        ]);
    }
}
