<?php

namespace ContainerHBSZ1zw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCoursesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.bhO19p3.App\Entity\Courses' shared service.
     *
     * @return \App\Entity\Courses
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.bhO19p3": it references class "App\\Entity\\Courses" but no such service exists.');
    }
}
