<?php

namespace ContainerHBSZ1zw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStudentsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hQ0iuw7.App\Entity\Students' shared service.
     *
     * @return \App\Entity\Students
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.hQ0iuw7": it references class "App\\Entity\\Students" but no such service exists.');
    }
}
