<?php

namespace ContainerGB9wXPp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BA9gThyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bA9gThy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bA9gThy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cr' => ['privates', 'App\\Repository\\StudentsRepository', 'getStudentsRepositoryService', true],
        ], [
            'cr' => 'App\\Repository\\StudentsRepository',
        ]);
    }
}
