<?php

namespace ContainerGB9wXPp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClassesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.IR1PjSX.App\Entity\Classes' shared service.
     *
     * @return \App\Entity\Classes
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.IR1PjSX": it references class "App\\Entity\\Classes" but no such service exists.');
    }
}
