<?php

namespace ContainerGB9wXPp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStudentsFormService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\StudentsForm' shared autowired service.
     *
     * @return \App\Form\StudentsForm
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/StudentsForm.php';

        return $container->privates['App\\Form\\StudentsForm'] = new \App\Form\StudentsForm();
    }
}
