<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGB9wXPp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGB9wXPp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGB9wXPp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGB9wXPp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGB9wXPp\App_KernelDevDebugContainer([
    'container.build_hash' => 'GB9wXPp',
    'container.build_id' => '279ac175',
    'container.build_time' => 1623916147,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGB9wXPp');
